---
/**:
  ros__parameters:
    general:
      pub_resolution: 'NATIVE'
      pub_downscale_factor: 1.0
      pub_frame_rate: 10.0
    depth:
      depth_mode: 'NONE'
      point_cloud_freq: 0.0
    video:
      publish_rgb: true
      publish_left_right: false
      publish_raw: false
